### ISSUE TITLE
AZ CLI was not found. 

### ISSUE THREAD

**Issue by jasonwbaxter** [humanascode/IaCBootcamp#1]
![image](https://user-images.githubusercontent.com/68377916/235658346-5433c099-090c-4d26-9e67-37ec2d50abed.png)

had to re-install the Azure CLI , Close the terminal + Visual studio code , and reopen vs code.

**Comment by humanascode** [comment]
Thank you for your comment Jason, I have added a comment in the latest commit 38c3a9a
